# Generated by Django 2.0.2 on 2018-03-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_id',
        ),
    ]
