# Generated by Django 2.0.2 on 2018-03-04 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0008_auto_20180304_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
