# Generated by Django 2.0.2 on 2018-03-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0016_auto_20180304_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
    ]
