# Generated by Django 2.0.2 on 2018-03-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0018_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
