# Generated by Django 2.0.2 on 2018-03-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0022_auto_20180304_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='auth_id',
        ),
    ]
