# Generated by Django 2.0.2 on 2018-03-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0024_auto_20180304_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auth_id',
            new_name='user_id',
        ),
    ]
