# Generated by Django 2.0.2 on 2018-03-04 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0025_auto_20180304_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 16, 10, 57, 72199)),
        ),
    ]
