# Generated by Django 2.0.2 on 2018-03-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0027_auto_20180304_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Articles.Category'),
        ),
    ]
