# Generated by Django 2.0.2 on 2018-03-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0029_auto_20180304_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author_id',
        ),
    ]
