# Generated by Django 2.0.2 on 2018-03-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0031_auto_20180304_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='Author',
        ),
    ]
