# Generated by Django 2.0.2 on 2018-03-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0032_auto_20180304_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
    ]
